// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
      // TODO: Handle this case.
      case TargetPlatform.linux:
      // TODO: Handle this case.
      case TargetPlatform.windows:
        return web;
      // TODO: Handle this case.
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfBvNn6UCoCtkX1bEAls0Ly_OfJCffLpM',
    appId: '1:913862869329:android:6f0f84411cdaf4e9979370',
    messagingSenderId: '913862869329',
    projectId: 'hrms-1eb10',
    storageBucket: 'hrms-1eb10.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    iosBundleId: 'com.redefine.hrms',
    apiKey: 'AIzaSyAPhS13IYNhm6hfZien18GiyoDenmiuLUk',
    appId: '1:913862869329:ios:773bda644c5b397d979370',
    messagingSenderId: '913862869329',
    projectId: 'hrms-1eb10',
    storageBucket: 'hrms-1eb10.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAA3Ka_9Jhnncf7mTly2AnJC8VT95MIz_8",
      authDomain: "yoga-buddy-266417.firebaseapp.com",
      databaseURL: "https://yoga-buddy-266417.firebaseio.com",
      projectId: "yoga-buddy-266417",
      storageBucket: "yoga-buddy-266417.appspot.com",
      messagingSenderId: "380744735472",
      appId: "1:380744735472:web:d16f75db3520f6b6234035",
      measurementId: "G-1J6ZPSTCE5");
}
